Shader "ZZZ"
{
    Properties
    {
        _BlockMaskTex("_BlockMaskTex", 2D) = "white" { }
        _ChannelMixTex("_ChannelMixTex", 2D) = "white" { }
        _CharacterRampTex("_CharacterRampTex", 2D) = "white" { }
        _EyeColorMap("_EyeColorMap", 2D) = "white" { }
        _LightTex("_LightTex", 2D) = "white" { }
        _MainTex("_MainTex", 2D) = "white" { }
        _MatCap2DArray("_MatCap2DArray", 2D) = "white" { }
        _MatCapBumpMapFx("_MatCapBumpMapFx", 2D) = "white" { }
        _MatCapTex("_MatCapTex", 2D) = "white" { }
        _MatCapTex2("_MatCapTex2", 2D) = "white" { }
        _MatCapTex3("_MatCapTex3", 2D) = "white" { }
        _MatCapTex4("_MatCapTex4", 2D) = "white" { }
        _MatCapTex5("_MatCapTex5", 2D) = "white" { }
        _MatCapTexFallback("_MatCapTexFallback", 2D) = "white" { }
        _MatCapTexFx("_MatCapTexFx", 2D) = "white" { }
        _OtherDataTex("_OtherDataTex", 2D) = "white" { }
        _OtherDataTex2("_OtherDataTex2", 2D) = "white" { }
        _OverrideOutlineTex("_OverrideOutlineTex", 2D) = "white" { }
        _OverrideRimGlowTexFX("_OverrideRimGlowTexFX", 2D) = "white" { }
        _ScreenMask("_ScreenMask", 2D) = "white" { }
        _ScreenTex("_ScreenTex", 2D) = "white" { }
        _SecondaryEmissionMaskTex("_SecondaryEmissionMaskTex", 2D) = "white" { }
        _SecondaryEmissionMaskTexForCGLighting("_SecondaryEmissionMaskTexForCGLighting", 2D) = "white" { }
        _SecondaryEmissionTex("_SecondaryEmissionTex", 2D) = "white" { }
        _SecondaryEmissionTexForCGLighting("_SecondaryEmissionTexForCGLighting", 2D) = "white" { }
        _SpecialWeaponEmissionMaskTex("_SpecialWeaponEmissionMaskTex", 2D) = "white" { }
        _SpecialWeaponEmissionTex("_SpecialWeaponEmissionTex", 2D) = "white" { }
        _StretchMask("_StretchMask", 2D) = "white" { }
        _ThreadMap("_ThreadMap", 2D) = "white" { }
        _TransitionTex("_TransitionTex", 2D) = "white" { }
        _AChannelColor("_AChannelColor", Color) = (1, 1, 1, 1)
        _AChannelColorPrecomputed("_AChannelColorPrecomputed", Color) = (1, 1, 1, 1)
        _AOParameters("_AOParameters", Color) = (1, 1, 1, 1)
        _AmbientColorCG("_AmbientColorCG", Color) = (1, 1, 1, 1)
        _BChannelColor("_BChannelColor", Color) = (1, 1, 1, 1)
        _BChannelColorPrecomputed("_BChannelColorPrecomputed", Color) = (1, 1, 1, 1)
        _BlinkOpacity("_BlinkOpacity", Color) = (1, 1, 1, 1)
        _BlockColorA("_BlockColorA", Color) = (1, 1, 1, 1)
        _BlockColorB("_BlockColorB", Color) = (1, 1, 1, 1)
        _BlockColorC("_BlockColorC", Color) = (1, 1, 1, 1)
        _BlockColorD("_BlockColorD", Color) = (1, 1, 1, 1)
        _BlockMoveSpeed("_BlockMoveSpeed", Color) = (1, 1, 1, 1)
        _CharacterMainLightData("_CharacterMainLightData", Color) = (1, 1, 1, 1)
        _CharacterMainLightData1("_CharacterMainLightData1", Color) = (1, 1, 1, 1)
        _Color("_Color", Color) = (1, 1, 1, 1)
        _ColorA("_ColorA", Color) = (1, 1, 1, 1)
        _ColorAForCGLighting("_ColorAForCGLighting", Color) = (1, 1, 1, 1)
        _ColorB("_ColorB", Color) = (1, 1, 1, 1)
        _ColorBForCGLighting("_ColorBForCGLighting", Color) = (1, 1, 1, 1)
        _ColorOverrideAlbedo("_ColorOverrideAlbedo", Color) = (1, 1, 1, 1)
        _DecolorizationContrast("_DecolorizationContrast", Color) = (1, 1, 1, 1)
        _DetailColor("_DetailColor", Color) = (1, 1, 1, 1)
        _DitherCenter("_DitherCenter", Color) = (1, 1, 1, 1)
        _EmissionColor("_EmissionColor", Color) = (1, 1, 1, 1)
        _EmissionColor2("_EmissionColor2", Color) = (1, 1, 1, 1)
        _EmissionColor3("_EmissionColor3", Color) = (1, 1, 1, 1)
        _EmissionColor4("_EmissionColor4", Color) = (1, 1, 1, 1)
        _EmissionColor5("_EmissionColor5", Color) = (1, 1, 1, 1)
        _FaceShadowPoint("_FaceShadowPoint", Color) = (1, 1, 1, 1)
        _FresnelColor("_FresnelColor", Color) = (1, 1, 1, 1)
        _FxTransparentValue("_FxTransparentValue", Color) = (1, 1, 1, 1)
        _FxUVDitherValue("_FxUVDitherValue", Color) = (1, 1, 1, 1)
        _GChannelColor("_GChannelColor", Color) = (1, 1, 1, 1)
        _GChannelColorPrecomputed("_GChannelColorPrecomputed", Color) = (1, 1, 1, 1)
        _HardLightColor("_HardLightColor", Color) = (1, 1, 1, 1)
        _HeadMatrixWS2OS0("_HeadMatrixWS2OS0", Color) = (1, 1, 1, 1)
        _HeadMatrixWS2OS1("_HeadMatrixWS2OS1", Color) = (1, 1, 1, 1)
        _HeadMatrixWS2OS2("_HeadMatrixWS2OS2", Color) = (1, 1, 1, 1)
        _HeadMatrixWS2OS3("_HeadMatrixWS2OS3", Color) = (1, 1, 1, 1)
        _LayerIDColor("_LayerIDColor", Color) = (1, 1, 1, 1)
        _LocalIndirectColor("_LocalIndirectColor", Color) = (1, 1, 1, 1)
        _LocalIndirectColor2("_LocalIndirectColor2", Color) = (1, 1, 1, 1)
        _LocalIndirectColor3("_LocalIndirectColor3", Color) = (1, 1, 1, 1)
        _LocalIndirectColor4("_LocalIndirectColor4", Color) = (1, 1, 1, 1)
        _LocalIndirectColor5("_LocalIndirectColor5", Color) = (1, 1, 1, 1)
        _MainPunctualLightData("_MainPunctualLightData", Color) = (1, 1, 1, 1)
        _MaskRChannelUVSpeed("_MaskRChannelUVSpeed", Color) = (1, 1, 1, 1)
        _MatCapColorTint("_MatCapColorTint", Color) = (1, 1, 1, 1)
        _MatCapColorTint2("_MatCapColorTint2", Color) = (1, 1, 1, 1)
        _MatCapColorTint3("_MatCapColorTint3", Color) = (1, 1, 1, 1)
        _MatCapColorTint4("_MatCapColorTint4", Color) = (1, 1, 1, 1)
        _MatCapColorTint5("_MatCapColorTint5", Color) = (1, 1, 1, 1)
        _MatCapColorTintFallback("_MatCapColorTintFallback", Color) = (1, 1, 1, 1)
        _MatCapColorTintFx("_MatCapColorTintFx", Color) = (1, 1, 1, 1)
        _MatCapParams("_MatCapParams", Color) = (1, 1, 1, 1)
        _MatCapParams2("_MatCapParams2", Color) = (1, 1, 1, 1)
        _MatCapParams3("_MatCapParams3", Color) = (1, 1, 1, 1)
        _MatCapParams4("_MatCapParams4", Color) = (1, 1, 1, 1)
        _MatCapParams5("_MatCapParams5", Color) = (1, 1, 1, 1)
        _MatCapReractParams("_MatCapReractParams", Color) = (1, 1, 1, 1)
        _MatCapReractParams2("_MatCapReractParams2", Color) = (1, 1, 1, 1)
        _MatCapReractParams3("_MatCapReractParams3", Color) = (1, 1, 1, 1)
        _MatCapReractParams4("_MatCapReractParams4", Color) = (1, 1, 1, 1)
        _MatCapReractParams5("_MatCapReractParams5", Color) = (1, 1, 1, 1)
        _MiddlePointPosition("_MiddlePointPosition", Color) = (1, 1, 1, 1)
        _OutlineColor("_OutlineColor", Color) = (1, 1, 1, 1)
        _OutlineColor2("_OutlineColor2", Color) = (1, 1, 1, 1)
        _OutlineColor3("_OutlineColor3", Color) = (1, 1, 1, 1)
        _OutlineColor4("_OutlineColor4", Color) = (1, 1, 1, 1)
        _OutlineColor5("_OutlineColor5", Color) = (1, 1, 1, 1)
        _OutlineColorFX("_OutlineColorFX", Color) = (1, 1, 1, 1)
        _OverrideColor("_OverrideColor", Color) = (1, 1, 1, 1)
        _OverrideMainLightColor("_OverrideMainLightColor", Color) = (1, 1, 1, 1)
        _OverrideMainLightColor2("_OverrideMainLightColor2", Color) = (1, 1, 1, 1)
        _OverrideMainLightColor3("_OverrideMainLightColor3", Color) = (1, 1, 1, 1)
        _OverrideMainLightColor4("_OverrideMainLightColor4", Color) = (1, 1, 1, 1)
        _OverrideMainLightColor5("_OverrideMainLightColor5", Color) = (1, 1, 1, 1)
        _OverrideOutlineColor("_OverrideOutlineColor", Color) = (1, 1, 1, 1)
        _OverrideOutlineSpeed("_OverrideOutlineSpeed", Color) = (1, 1, 1, 1)
        _OverrideRimGlowColor("_OverrideRimGlowColor", Color) = (1, 1, 1, 1)
        _OverrideRimGlowSpeed("_OverrideRimGlowSpeed", Color) = (1, 1, 1, 1)
        _PlaneXZScale("_PlaneXZScale", Color) = (1, 1, 1, 1)
        _PointPosition("_PointPosition", Color) = (1, 1, 1, 1)
        _PointPositionForCGLighting("_PointPositionForCGLighting", Color) = (1, 1, 1, 1)
        _PropertyColor("_PropertyColor", Color) = (1, 1, 1, 1)
        _PropertyMask2UVSpeed("_PropertyMask2UVSpeed", Color) = (1, 1, 1, 1)
        _PropertyMaskUVSpeed("_PropertyMaskUVSpeed", Color) = (1, 1, 1, 1)
        _PropertyNormalUVSpeed("_PropertyNormalUVSpeed", Color) = (1, 1, 1, 1)
        _PropertyTexUVSpeed("_PropertyTexUVSpeed", Color) = (1, 1, 1, 1)
        _RChannelColor("_RChannelColor", Color) = (1, 1, 1, 1)
        _RChannelColorPrecomputed("_RChannelColorPrecomputed", Color) = (1, 1, 1, 1)
        _RampTexParams0("_RampTexParams0", Color) = (1, 1, 1, 1)
        _RampTexParams1("_RampTexParams1", Color) = (1, 1, 1, 1)
        _RampTexParams2("_RampTexParams2", Color) = (1, 1, 1, 1)
        _RefractParam("_RefractParam", Color) = (1, 1, 1, 1)
        _RefractParam2("_RefractParam2", Color) = (1, 1, 1, 1)
        _RefractParam3("_RefractParam3", Color) = (1, 1, 1, 1)
        _RefractParam4("_RefractParam4", Color) = (1, 1, 1, 1)
        _RefractParam5("_RefractParam5", Color) = (1, 1, 1, 1)
        _RefractParamFallback("_RefractParamFallback", Color) = (1, 1, 1, 1)
        _RimGlowLightColor("_RimGlowLightColor", Color) = (1, 1, 1, 1)
        _RimGlowLightColor2("_RimGlowLightColor2", Color) = (1, 1, 1, 1)
        _RimGlowLightColor3("_RimGlowLightColor3", Color) = (1, 1, 1, 1)
        _RimGlowLightColor4("_RimGlowLightColor4", Color) = (1, 1, 1, 1)
        _RimGlowLightColor5("_RimGlowLightColor5", Color) = (1, 1, 1, 1)
        _RimGlowShadowColor("_RimGlowShadowColor", Color) = (1, 1, 1, 1)
        _RimGlowShadowColor2("_RimGlowShadowColor2", Color) = (1, 1, 1, 1)
        _RimGlowShadowColor3("_RimGlowShadowColor3", Color) = (1, 1, 1, 1)
        _ScreenColor("_ScreenColor", Color) = (1, 1, 1, 1)
        _ScreenImageUvMove("_ScreenImageUvMove", Color) = (1, 1, 1, 1)
        _ScreenTexRotationAxis("_ScreenTexRotationAxis", Color) = (1, 1, 1, 1)
        _SecondaryEmissionColor("_SecondaryEmissionColor", Color) = (1, 1, 1, 1)
        _SecondaryEmissionColorForCGLighting("_SecondaryEmissionColorForCGLighting", Color) = (1, 1, 1, 1)
        _SecondaryEmissionParam("_SecondaryEmissionParam", Color) = (1, 1, 1, 1)
        _SecondaryEmissionTexSpeed("_SecondaryEmissionTexSpeed", Color) = (1, 1, 1, 1)
        _ShadowColor("_ShadowColor", Color) = (1, 1, 1, 1)
        _ShadowColor2("_ShadowColor2", Color) = (1, 1, 1, 1)
        _ShadowColor3("_ShadowColor3", Color) = (1, 1, 1, 1)
        _ShadowColor4("_ShadowColor4", Color) = (1, 1, 1, 1)
        _ShadowColor5("_ShadowColor5", Color) = (1, 1, 1, 1)
        _ShallowColor("_ShallowColor", Color) = (1, 1, 1, 1)
        _ShallowColor2("_ShallowColor2", Color) = (1, 1, 1, 1)
        _ShallowColor3("_ShallowColor3", Color) = (1, 1, 1, 1)
        _ShallowColor4("_ShallowColor4", Color) = (1, 1, 1, 1)
        _ShallowColor5("_ShallowColor5", Color) = (1, 1, 1, 1)
        _SilkFresnelColorEdge("_SilkFresnelColorEdge", Color) = (1, 1, 1, 1)
        _SilkFresnelColorFront("_SilkFresnelColorFront", Color) = (1, 1, 1, 1)
        _SilkPackedParams0("_SilkPackedParams0", Color) = (1, 1, 1, 1)
        _SoftLightColor("_SoftLightColor", Color) = (1, 1, 1, 1)
        _SpecSocketBindPoseMat0("_SpecSocketBindPoseMat0", Color) = (1, 1, 1, 1)
        _SpecSocketBindPoseMat1("_SpecSocketBindPoseMat1", Color) = (1, 1, 1, 1)
        _SpecSocketBindPoseMat2("_SpecSocketBindPoseMat2", Color) = (1, 1, 1, 1)
        _SpecSocketBindPoseMat3("_SpecSocketBindPoseMat3", Color) = (1, 1, 1, 1)
        _SpecSocketPosOffset("_SpecSocketPosOffset", Color) = (1, 1, 1, 1)
        _SpecialWeaponEmissionColor("_SpecialWeaponEmissionColor", Color) = (1, 1, 1, 1)
        _SpecialWeaponEmissionColor2("_SpecialWeaponEmissionColor2", Color) = (1, 1, 1, 1)
        _SpecialWeaponEmissionTexSpeed("_SpecialWeaponEmissionTexSpeed", Color) = (1, 1, 1, 1)
        _SpecialWeaponMergeParam01("_SpecialWeaponMergeParam01", Color) = (1, 1, 1, 1)
        _SpecialWeaponMergeParam02("_SpecialWeaponMergeParam02", Color) = (1, 1, 1, 1)
        _SpecialWeaponMergeParam03("_SpecialWeaponMergeParam03", Color) = (1, 1, 1, 1)
        _SpecularColor("_SpecularColor", Color) = (1, 1, 1, 1)
        _SpecularColor2("_SpecularColor2", Color) = (1, 1, 1, 1)
        _SpecularColor3("_SpecularColor3", Color) = (1, 1, 1, 1)
        _SpecularColor4("_SpecularColor4", Color) = (1, 1, 1, 1)
        _SpecularColor5("_SpecularColor5", Color) = (1, 1, 1, 1)
        _StretchToPoint("_StretchToPoint", Color) = (1, 1, 1, 1)
        _StretchVector("_StretchVector", Color) = (1, 1, 1, 1)
        _TransitionColor("_TransitionColor", Color) = (1, 1, 1, 1)
        _AbnormalProperty("_AbnormalProperty", Float) = 0
        _AbnormalPropertyBurn("_AbnormalPropertyBurn", Float) = 0
        _AbnormalPropertyElectro("_AbnormalPropertyElectro", Float) = 0
        _AbnormalPropertyFreeze("_AbnormalPropertyFreeze", Float) = 0
        _AdditionalLightIntensity("_AdditionalLightIntensity", Float) = 0
        _AlbedoSmoothness("_AlbedoSmoothness", Float) = 0
        _AlbedoSmoothness2("_AlbedoSmoothness2", Float) = 0
        _AlbedoSmoothness3("_AlbedoSmoothness3", Float) = 0
        _AlbedoSmoothness4("_AlbedoSmoothness4", Float) = 0
        _AlbedoSmoothness5("_AlbedoSmoothness5", Float) = 0
        _AlphaClip("_AlphaClip", Float) = 0
        _AlphaDstBlend("_AlphaDstBlend", Float) = 0
        _AlphaSrcBlend("_AlphaSrcBlend", Float) = 0
        _AmbientColorScale("_AmbientColorScale", Float) = 0
        _Anisotropy("_Anisotropy", Float) = 0
        _BShift("_BShift", Float) = 0
        _Blink("_Blink", Float) = 0
        _BlinkFrequency("_BlinkFrequency", Float) = 0
        _BrightMultiplier("_BrightMultiplier", Float) = 0
        _BrightMultiplier2("_BrightMultiplier2", Float) = 0
        _BrightMultiplier3("_BrightMultiplier3", Float) = 0
        _BrightMultiplier4("_BrightMultiplier4", Float) = 0
        _BrightMultiplier5("_BrightMultiplier5", Float) = 0
        _BumpScale("_BumpScale", Float) = 0
        _CameraToLightRadian("_CameraToLightRadian", Float) = 0
        _CenterMinAlpha("_CenterMinAlpha", Float) = 0
        _ChannelMixerUsingUV4("_ChannelMixerUsingUV4", Float) = 0
        _CharacterHalfResAlphaDstBlend("_CharacterHalfResAlphaDstBlend", Float) = 0
        _CharacterHalfResAlphaSrcBlend("_CharacterHalfResAlphaSrcBlend", Float) = 0
        _CharacterHalfResDstBlend("_CharacterHalfResDstBlend", Float) = 0
        _CharacterHalfResSrcBlend("_CharacterHalfResSrcBlend", Float) = 0
        _CharacterSimplify("_CharacterSimplify", Float) = 0
        _CharacterStencil("_CharacterStencil", Float) = 0
        _CharacterStencilCompDepth("_CharacterStencilCompDepth", Float) = 0
        _CharacterStencilDepth("_CharacterStencilDepth", Float) = 0
        _CharacterStencilOp("_CharacterStencilOp", Float) = 0
        _ClipPlane("_ClipPlane", Float) = 0
        _ClipPlaneXZ("_ClipPlaneXZ", Float) = 0
        _ClipSpaceXOffset("_ClipSpaceXOffset", Float) = 0
        _ClipSpaceYOffset("_ClipSpaceYOffset", Float) = 0
        _ColorBlocks("_ColorBlocks", Float) = 0
        _Cull("_Cull", Float) = 0
        _Cutoff("_Cutoff", Float) = 0
        _DarkAOScale("_DarkAOScale", Float) = 0
        _DetailNormalMapScale("_DetailNormalMapScale", Float) = 0
        _DiffuseFade("_DiffuseFade", Float) = 0
        _DiffuseFade2("_DiffuseFade2", Float) = 0
        _DiffuseFade3("_DiffuseFade3", Float) = 0
        _DiffuseFade4("_DiffuseFade4", Float) = 0
        _DiffuseFade5("_DiffuseFade5", Float) = 0
        _Dither("_Dither", Float) = 0
        _DitherAlpha("_DitherAlpha", Float) = 0
        _DitherAlpha2("_DitherAlpha2", Float) = 0
        _DoubleSided("_DoubleSided", Float) = 0
        _DstBlend("_DstBlend", Float) = 0
        _Emission("_Emission", Float) = 0
        _FixNeck("_FixNeck", Float) = 0
        _FixedLightDirection("_FixedLightDirection", Float) = 0
        _FresnelFlashing("_FresnelFlashing", Float) = 0
        _FresnelMaskWidth("_FresnelMaskWidth", Float) = 0
        _FresnelWidth("_FresnelWidth", Float) = 0
        _GShift("_GShift", Float) = 0
        _Glitch("_Glitch", Float) = 0
        _GlossMapScale("_GlossMapScale", Float) = 0
        _Glossiness("_Glossiness", Float) = 0
        _GlossyReflections("_GlossyReflections", Float) = 0
        _HalfResAlphaDstBlend("_HalfResAlphaDstBlend", Float) = 0
        _HalfResAlphaSrcBlend("_HalfResAlphaSrcBlend", Float) = 0
        _HalfResDstBlend("_HalfResDstBlend", Float) = 0
        _HalfResSrcBlend("_HalfResSrcBlend", Float) = 0
        _HardLight("_HardLight", Float) = 0
        _HardLightWidth("_HardLightWidth", Float) = 0
        _HighlightShape("_HighlightShape", Float) = 0
        _HighlightShape2("_HighlightShape2", Float) = 0
        _HighlightShape3("_HighlightShape3", Float) = 0
        _HighlightShape4("_HighlightShape4", Float) = 0
        _HighlightShape5("_HighlightShape5", Float) = 0
        _IgnoreTimeScale("_IgnoreTimeScale", Float) = 0
        _IterateOver("_IterateOver", Float) = 0
        _Length("_Length", Float) = 0
        _LerpPosition("_LerpPosition", Float) = 0
        _LerpPositionForCGLighting("_LerpPositionForCGLighting", Float) = 0
        _LightDirectionFromCamera("_LightDirectionFromCamera", Float) = 0
        _LightMapUVFlip("_LightMapUVFlip", Float) = 0
        _LightSource("_LightSource", Float) = 0
        _LightSourceForCGLighting("_LightSourceForCGLighting", Float) = 0
        _LineBrightness("_LineBrightness", Float) = 0
        _LineGlitch("_LineGlitch", Float) = 0
        _LineThresholdMax("_LineThresholdMax", Float) = 0
        _LineThresholdMin("_LineThresholdMin", Float) = 0
        _MarkAsGhostMask("_MarkAsGhostMask", Float) = 0
        _MarkAsGlitchMask("_MarkAsGlitchMask", Float) = 0
        _MarkAsIgnisFatuusMask("_MarkAsIgnisFatuusMask", Float) = 0
        _MarkAsVfxMask("_MarkAsVfxMask", Float) = 0
        _MaskTexFactor("_MaskTexFactor", Float) = 0
        _MatCap("_MatCap", Float) = 0
        _MatCapAlphaBurst("_MatCapAlphaBurst", Float) = 0
        _MatCapAlphaBurst2("_MatCapAlphaBurst2", Float) = 0
        _MatCapAlphaBurst3("_MatCapAlphaBurst3", Float) = 0
        _MatCapAlphaBurst4("_MatCapAlphaBurst4", Float) = 0
        _MatCapAlphaBurst5("_MatCapAlphaBurst5", Float) = 0
        _MatCapAlphaBurstFallback("_MatCapAlphaBurstFallback", Float) = 0
        _MatCapAlphaBurstFx("_MatCapAlphaBurstFx", Float) = 0
        _MatCapBlendMode("_MatCapBlendMode", Float) = 0
        _MatCapBlendMode2("_MatCapBlendMode2", Float) = 0
        _MatCapBlendMode3("_MatCapBlendMode3", Float) = 0
        _MatCapBlendMode4("_MatCapBlendMode4", Float) = 0
        _MatCapBlendMode5("_MatCapBlendMode5", Float) = 0
        _MatCapBlendModeFallback("_MatCapBlendModeFallback", Float) = 0
        _MatCapBlendModeFx("_MatCapBlendModeFx", Float) = 0
        _MatCapBumpScaleFx("_MatCapBumpScaleFx", Float) = 0
        _MatCapColorBurst("_MatCapColorBurst", Float) = 0
        _MatCapColorBurst2("_MatCapColorBurst2", Float) = 0
        _MatCapColorBurst3("_MatCapColorBurst3", Float) = 0
        _MatCapColorBurst4("_MatCapColorBurst4", Float) = 0
        _MatCapColorBurst5("_MatCapColorBurst5", Float) = 0
        _MatCapColorBurstFallback("_MatCapColorBurstFallback", Float) = 0
        _MatCapColorBurstFx("_MatCapColorBurstFx", Float) = 0
        _MatCapFX("_MatCapFX", Float) = 0
        _MatCapNormalUSpeedFx("_MatCapNormalUSpeedFx", Float) = 0
        _MatCapNormalVSpeedFx("_MatCapNormalVSpeedFx", Float) = 0
        _MatCapRefract("_MatCapRefract", Float) = 0
        _MatCapRefract2("_MatCapRefract2", Float) = 0
        _MatCapRefract3("_MatCapRefract3", Float) = 0
        _MatCapRefract4("_MatCapRefract4", Float) = 0
        _MatCapRefract5("_MatCapRefract5", Float) = 0
        _MatCapRefractFallback("_MatCapRefractFallback", Float) = 0
        _MatCapTexID("_MatCapTexID", Float) = 0
        _MatCapTexID2("_MatCapTexID2", Float) = 0
        _MatCapTexID3("_MatCapTexID3", Float) = 0
        _MatCapTexID4("_MatCapTexID4", Float) = 0
        _MatCapTexID5("_MatCapTexID5", Float) = 0
        _MatCapUSpeed("_MatCapUSpeed", Float) = 0
        _MatCapUSpeed2("_MatCapUSpeed2", Float) = 0
        _MatCapUSpeed3("_MatCapUSpeed3", Float) = 0
        _MatCapUSpeed4("_MatCapUSpeed4", Float) = 0
        _MatCapUSpeed5("_MatCapUSpeed5", Float) = 0
        _MatCapUSpeedFallback("_MatCapUSpeedFallback", Float) = 0
        _MatCapUSpeedFx("_MatCapUSpeedFx", Float) = 0
        _MatCapVSpeed("_MatCapVSpeed", Float) = 0
        _MatCapVSpeed2("_MatCapVSpeed2", Float) = 0
        _MatCapVSpeed3("_MatCapVSpeed3", Float) = 0
        _MatCapVSpeed4("_MatCapVSpeed4", Float) = 0
        _MatCapVSpeed5("_MatCapVSpeed5", Float) = 0
        _MatCapVSpeedFallback("_MatCapVSpeedFallback", Float) = 0
        _MatCapVSpeedFx("_MatCapVSpeedFx", Float) = 0
        _MatcapBrightnessAlpha("_MatcapBrightnessAlpha", Float) = 0
        _MaterialNum("_MaterialNum", Float) = 0
        _MaxOutlineZOffset("_MaxOutlineZOffset", Float) = 0
        _Metallic("_Metallic", Float) = 0
        _Mode("_Mode", Float) = 0
        _ModelSize("_ModelSize", Float) = 0
        _ModelSize2("_ModelSize2", Float) = 0
        _ModelSize3("_ModelSize3", Float) = 0
        _ModelSize4("_ModelSize4", Float) = 0
        _ModelSize5("_ModelSize5", Float) = 0
        _MultiplyAlbedo("_MultiplyAlbedo", Float) = 0
        _MultiplyAlbedoForCGLighting("_MultiplyAlbedoForCGLighting", Float) = 0
        _MultiplySrcColor("_MultiplySrcColor", Float) = 0
        _NoiseScale("_NoiseScale", Float) = 0
        _NormalThreshold("_NormalThreshold", Float) = 0
        _NoseLineHoriDisp("_NoseLineHoriDisp", Float) = 0
        _NoseLineLkDnDisp("_NoseLineLkDnDisp", Float) = 0
        _NoseLineScale("_NoseLineScale", Float) = 0
        _NoseSpecularScale("_NoseSpecularScale", Float) = 0
        _OcclusionStrength("_OcclusionStrength", Float) = 0
        _Outline("_Outline", Float) = 0
        _OutlineFX("_OutlineFX", Float) = 0
        _OutlineWidth("_OutlineWidth", Float) = 0
        _OutlineWidthFX("_OutlineWidthFX", Float) = 0
        _OverlayTexScale("_OverlayTexScale", Float) = 0
        _Override("_Override", Float) = 0
        _Override2Tone("_Override2Tone", Float) = 0
        _Override2ToneBlendMode("_Override2ToneBlendMode", Float) = 0
        _Override2ToneBlendModeForCGLighting("_Override2ToneBlendModeForCGLighting", Float) = 0
        _Override2ToneForCGLighting("_Override2ToneForCGLighting", Float) = 0
        _Override2ToneMultiplyAlbedo("_Override2ToneMultiplyAlbedo", Float) = 0
        _Override2ToneMultiplyAlbedoForCGLighting("_Override2ToneMultiplyAlbedoForCGLighting", Float) = 0
        _OverrideMainLightParam("_OverrideMainLightParam", Float) = 0
        _OverrideMainLightParam2("_OverrideMainLightParam2", Float) = 0
        _OverrideMainLightParam3("_OverrideMainLightParam3", Float) = 0
        _OverrideMainLightParam4("_OverrideMainLightParam4", Float) = 0
        _OverrideMainLightParam5("_OverrideMainLightParam5", Float) = 0
        _OverrideOutline("_OverrideOutline", Float) = 0
        _OverrideOutlineUseUV2("_OverrideOutlineUseUV2", Float) = 0
        _OverrideRimGlow("_OverrideRimGlow", Float) = 0
        _OverrideRimGlowMode("_OverrideRimGlowMode", Float) = 0
        _OverrideRimGlowUseUV2("_OverrideRimGlowUseUV2", Float) = 0
        _Parallax("_Parallax", Float) = 0
        _PerObjectShadowData("_PerObjectShadowData", Float) = 0
        _PerObjectShadowIntensity("_PerObjectShadowIntensity", Float) = 0
        _PerObjectShadowIntensity2("_PerObjectShadowIntensity2", Float) = 0
        _PerObjectShadowIntensity3("_PerObjectShadowIntensity3", Float) = 0
        _PerObjectShadowIntensity4("_PerObjectShadowIntensity4", Float) = 0
        _PerObjectShadowIntensity5("_PerObjectShadowIntensity5", Float) = 0
        _PlaneClipReverse("_PlaneClipReverse", Float) = 0
        _PointSpace("_PointSpace", Float) = 0
        _PointSpaceForCGLighting("_PointSpaceForCGLighting", Float) = 0
        _PowMax("_PowMax", Float) = 0
        _PowMin("_PowMin", Float) = 0
        _PropertyMask2Channel("_PropertyMask2Channel", Float) = 0
        _PropertyMask2UseUV2("_PropertyMask2UseUV2", Float) = 0
        _PropertyMaskChannel("_PropertyMaskChannel", Float) = 0
        _PropertyMaskUVFlipSpeed("_PropertyMaskUVFlipSpeed", Float) = 0
        _PropertyMaskUseUV2("_PropertyMaskUseUV2", Float) = 0
        _PropertyNormalUseUV2("_PropertyNormalUseUV2", Float) = 0
        _PropertyTexUVFlipSpeed("_PropertyTexUVFlipSpeed", Float) = 0
        _PropertyTexUseUV2("_PropertyTexUseUV2", Float) = 0
        _PropertyType("_PropertyType", Float) = 0
        _RShift("_RShift", Float) = 0
        _RampSource("_RampSource", Float) = 0
        _ReceiveAddShadows("_ReceiveAddShadows", Float) = 0
        _ReceiveShadows("_ReceiveShadows", Float) = 0
        _ReceiveStencilShadow("_ReceiveStencilShadow", Float) = 0
        _RefractDepth("_RefractDepth", Float) = 0
        _RefractDepth2("_RefractDepth2", Float) = 0
        _RefractDepth3("_RefractDepth3", Float) = 0
        _RefractDepth4("_RefractDepth4", Float) = 0
        _RefractDepth5("_RefractDepth5", Float) = 0
        _RefractDepthFallback("_RefractDepthFallback", Float) = 0
        _RenderType("_RenderType", Float) = 0
        _ReversePlaneXZ("_ReversePlaneXZ", Float) = 0
        _RimGlow("_RimGlow", Float) = 0
        _ScreenImage("_ScreenImage", Float) = 0
        _ScreenMaskUV("_ScreenMaskUV", Float) = 0
        _ScreenScale("_ScreenScale", Float) = 0
        _ScreenTexRotation("_ScreenTexRotation", Float) = 0
        _SecondaryEmission("_SecondaryEmission", Float) = 0
        _SecondaryEmissionChannel("_SecondaryEmissionChannel", Float) = 0
        _SecondaryEmissionChannelForCGLighting("_SecondaryEmissionChannelForCGLighting", Float) = 0
        _SecondaryEmissionForCGLighting("_SecondaryEmissionForCGLighting", Float) = 0
        _SecondaryEmissionMaskChannel("_SecondaryEmissionMaskChannel", Float) = 0
        _SecondaryEmissionMaskChannelForCGLighting("_SecondaryEmissionMaskChannelForCGLighting", Float) = 0
        _SecondaryEmissionTexRotation("_SecondaryEmissionTexRotation", Float) = 0
        _SecondaryEmissionTexRotationForCGLighting("_SecondaryEmissionTexRotationForCGLighting", Float) = 0
        _SecondaryEmissionUseUV2("_SecondaryEmissionUseUV2", Float) = 0
        _SecondaryEmissionUseUV2ForCGLighting("_SecondaryEmissionUseUV2ForCGLighting", Float) = 0
        _ShadowColorFadeByZ("_ShadowColorFadeByZ", Float) = 0
        _ShadowCull("_ShadowCull", Float) = 0
        _ShadowDitherOff("_ShadowDitherOff", Float) = 0
        _ShadowNormalBias("_ShadowNormalBias", Float) = 0
        _ShadowZOffset("_ShadowZOffset", Float) = 0
        _ShadowZOffsetWholeMesh("_ShadowZOffsetWholeMesh", Float) = 0
        _ShadowmapSmoothness("_ShadowmapSmoothness", Float) = 0
        _ShapeSoftness("_ShapeSoftness", Float) = 0
        _ShapeSoftness2("_ShapeSoftness2", Float) = 0
        _ShapeSoftness3("_ShapeSoftness3", Float) = 0
        _ShapeSoftness4("_ShapeSoftness4", Float) = 0
        _ShapeSoftness5("_ShapeSoftness5", Float) = 0
        _ShiftAngle("_ShiftAngle", Float) = 0
        _ShiftAngleForCGLighting("_ShiftAngleForCGLighting", Float) = 0
        _SkinMatId("_SkinMatId", Float) = 0
        _SmoothnessTextureChannel("_SmoothnessTextureChannel", Float) = 0
        _SoftLight("_SoftLight", Float) = 0
        _SoftLightWidth("_SoftLightWidth", Float) = 0
        _Softness("_Softness", Float) = 0
        _SoftnessForCGLighting("_SoftnessForCGLighting", Float) = 0
        _SpecIntensity("_SpecIntensity", Float) = 0
        _SpecSocketBoneIndex("_SpecSocketBoneIndex", Float) = 0
        _SpecSocketGPUAnimInstanceID("_SpecSocketGPUAnimInstanceID", Float) = 0
        _SpecSocketTotalNumberOfBones("_SpecSocketTotalNumberOfBones", Float) = 0
        _SpecialWeaponEmission("_SpecialWeaponEmission", Float) = 0
        _SpecularHighlights("_SpecularHighlights", Float) = 0
        _SpecularRange("_SpecularRange", Float) = 0
        _SpecularRange2("_SpecularRange2", Float) = 0
        _SpecularRange3("_SpecularRange3", Float) = 0
        _SpecularRange4("_SpecularRange4", Float) = 0
        _SpecularRange5("_SpecularRange5", Float) = 0
        _SrcBlend("_SrcBlend", Float) = 0
        _SssWidth("_SssWidth", Float) = 0
        _SssWidth2("_SssWidth2", Float) = 0
        _StencilComFunc("_StencilComFunc", Float) = 0
        _StencilReadMask("_StencilReadMask", Float) = 0
        _StencilRef("_StencilRef", Float) = 0
        _StencilRefShadow("_StencilRefShadow", Float) = 0
        _StencilWriteMask("_StencilWriteMask", Float) = 0
        _StencilWriteMaskShadow("_StencilWriteMaskShadow", Float) = 0
        _StretchDirection("_StretchDirection", Float) = 0
        _StretchDistance("_StretchDistance", Float) = 0
        _StretchPercentage("_StretchPercentage", Float) = 0
        _Surface("_Surface", Float) = 0
        _SymmetryUV("_SymmetryUV", Float) = 0
        _TabSelection("_TabSelection", Float) = 0
        _ToonSpecular("_ToonSpecular", Float) = 0
        _ToonSpecular2("_ToonSpecular2", Float) = 0
        _ToonSpecular3("_ToonSpecular3", Float) = 0
        _ToonSpecular4("_ToonSpecular4", Float) = 0
        _ToonSpecular5("_ToonSpecular5", Float) = 0
        _TransSpeed("_TransSpeed", Float) = 0
        _Transition("_Transition", Float) = 0
        _TransitionCompletion("_TransitionCompletion", Float) = 0
        _TransitionWidth("_TransitionWidth", Float) = 0
        _UI("_UI", Float) = 0
        _UVSec("_UVSec", Float) = 0
        _UseAlpha("_UseAlpha", Float) = 0
        _UseAlphaFX("_UseAlphaFX", Float) = 0
        _UseChannelMixer("_UseChannelMixer", Float) = 0
        _UseClipPlane("_UseClipPlane", Float) = 0
        _UseDitherCenter("_UseDitherCenter", Float) = 0
        _UseFaceShadowPoint("_UseFaceShadowPoint", Float) = 0
        _UseInvSecondaryEmissionMask("_UseInvSecondaryEmissionMask", Float) = 0
        _UseMatCapMask("_UseMatCapMask", Float) = 0
        _UseOverlayTex("_UseOverlayTex", Float) = 0
        _UseShadowFadeMask("_UseShadowFadeMask", Float) = 0
        _UseVertexMaterialID("_UseVertexMaterialID", Float) = 0
        _VertexOffset("_VertexOffset", Float) = 0
        _VertexStretch("_VertexStretch", Float) = 0
        _VolumeLutScale("_VolumeLutScale", Float) = 0
        _VolumeLutScale2("_VolumeLutScale2", Float) = 0
        _VolumeLutScale3("_VolumeLutScale3", Float) = 0
        _VolumeLutScale4("_VolumeLutScale4", Float) = 0
        _VolumeLutScale5("_VolumeLutScale5", Float) = 0
        _XOffset("_XOffset", Float) = 0
        _XOffsetEnter("_XOffsetEnter", Float) = 0
        _XOffsetNew("_XOffsetNew", Float) = 0
        _YOffset("_YOffset", Float) = 0
        _YOffsetEnter("_YOffsetEnter", Float) = 0
        _ZOffset("_ZOffset", Float) = 0
        _ZTest("_ZTest", Float) = 0
        _ZTestPreZ("_ZTestPreZ", Float) = 0
        _ZWrite("_ZWrite", Float) = 0
        _ZWritePreZ("_ZWritePreZ", Float) = 0
    }
    SubShader
    {
        Tags { "RenderType" = "Opaque" "Queue" = "Geometry" }
        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "UnityCG.cginc"
            sampler2D _MainTex;
            float4 _MainTex_ST;
            fixed4 _Color;
            struct appdata { float4 vertex : POSITION; float2 uv : TEXCOORD0; };
            struct v2f { float2 uv : TEXCOORD0; float4 vertex : SV_POSITION; };
            v2f vert(appdata v) { v2f o; o.vertex = UnityObjectToClipPos(v.vertex); o.uv = TRANSFORM_TEX(v.uv, _MainTex); return o; }
            fixed4 frag(v2f i) : SV_Target { return tex2D(_MainTex, i.uv) * _Color; }
            ENDCG
        }

        Pass
        {
            Name "DepthOnly"
            Tags
            {
                "LightMode" = "DepthOnly"
            }
            ZWrite On
            ColorMask R
            HLSLPROGRAM
            #pragma target 2.0
            #pragma vertex DepthOnlyVertex
            #pragma fragment DepthOnlyFragment
            #pragma shader_feature_local _ALPHATEST_ON
            #pragma multi_compile_fragment _ LOD_FADE_CROSSFADE
            #pragma multi_compile_instancing
            #include_with_pragmas "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DOTS.hlsl"
            #include "Assets/unity-shadertoy-validation/Common/Shaders/ShadertoyDepthOnlyPass.hlsl"
            ENDHLSL
        }
    }
}
